// Generated by tmpl
// https://github.com/benbjohnson/tmpl
//
// DO NOT EDIT!
// Source: watcher.gen.go.tmpl

package kubernetes

import (
	"context"
	"fmt"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	routev1 "github.com/openshift/api/route/v1"
	"github.com/openshift/client-go/route/clientset/versioned"
	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	extensionsv1beta1 "k8s.io/api/extensions/v1beta1"
	networkingv1 "k8s.io/api/networking/v1"
	networkingv1beta1 "k8s.io/api/networking/v1beta1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/watch"
	"k8s.io/client-go/kubernetes"
)

/*
 * K8s同步watcher
 *     每一个watcher是一个单独的goroutine，由两个channel
 *     发过来的消息触发进行工作。其一是k8s api的watch消息，
 *     当监控的对象发生改变时，channel会收到事件，watcher
 *     只关注add和delete；另一个channel是每隔10分钟的tick，
 *     当watcher 10分钟内没有收到监控对象的添加删除事件时，
 *     会直接调用k8s list api拿到所有监控资源，和内存数据
 *     进行比对。此外，当API watcher退出时，ctx会自动关闭，
 *     watcher也会退出。
 */
type CoreV1NodeWatcher struct {
	ctx       context.Context
	client    *kubernetes.Clientset
	namespace string

	m       sync.RWMutex
	entries map[string]*corev1.Node
	version uint64

	hasError uint32
	errorMsg atomic.Value
}

func (w *CoreV1NodeWatcher) Type() string {
	return "NodeWatcher"
}

func (w *CoreV1NodeWatcher) Version() uint64 {
	return atomic.LoadUint64(&w.version)
}

func (w *CoreV1NodeWatcher) Error() string {
	if atomic.LoadUint32(&w.hasError) == 0 {
		return ""
	}
	atomic.StoreUint32(&w.hasError, 0)
	return w.errorMsg.Load().(string)
}

func (w *CoreV1NodeWatcher) Entries() []runtime.Object {
	w.m.RLock()
	entries := make([]runtime.Object, 0, len(w.entries))
	for _, e := range w.entries {
		entries = append(entries, e)
	}
	w.m.RUnlock()
	return entries
}

func (w *CoreV1NodeWatcher) run() {
	var watcher watch.Interface
	var err error

	log.Info("Nodes watcher starting")
PREPARE:
	for {
		select {
		case <-w.ctx.Done():
			log.Info("Nodes watcher stopped")
			return
		default:
			watcher, err = w.client.CoreV1().Nodes().Watch(w.ctx, metav1.ListOptions{})
			if err == nil {
				break PREPARE
			}
			errMsg := fmt.Sprintf("Nodes watcher Watch failed: %v", err)
			log.Warning(errMsg)
			w.errorMsg.Store(errMsg)
			atomic.StoreUint32(&w.hasError, 1)
			time.Sleep(time.Minute)
		}
	}

	log.Info("Nodes watcher started")
	ticker := time.NewTicker(LIST_INTERVAL)
	lastUpdate := time.Now()
	lastRefresh := time.Now()
LOOP:
	for {
		select {
		case <-w.ctx.Done():
			log.Info("Nodes watcher stopped")
			break LOOP
		case ev, ok := <-watcher.ResultChan():
			if !ok {
				log.Debugf("Nodes watcher try rewatch")
				newWatcher, err := w.client.CoreV1().Nodes().Watch(w.ctx, metav1.ListOptions{})
				if err != nil {
					errMsg := fmt.Sprintf("Nodes watcher Watch failed: %v", err)
					log.Warning(errMsg)
					w.errorMsg.Store(errMsg)
					atomic.StoreUint32(&w.hasError, 1)
					time.Sleep(time.Minute)
				} else {
					watcher = newWatcher
				}
				continue LOOP
			}
			if ev.Type == watch.Error {
				if to, ok := ev.Object.(*metav1.Status); ok {
					if strings.Contains(to.Message, "RST_STREAM") {
						// 正常的超时
						log.Debugf("Nodes watcher timeout rewatch")
						continue
					}
				}
				log.Warningf("Nodes watcher has error: %v", ev.Object)
				continue
			}
			if ev.Type != watch.Added && ev.Type != watch.Deleted && ev.Type != watch.Modified {
				continue
			}
			el, ok := ev.Object.(*corev1.Node)
			if !ok {
				continue
			}
			id := string(el.ObjectMeta.UID)
			// 只有删除时检查是否需要更新版本号，其余消息直接更新map内容
			if ev.Type == watch.Deleted {
				if _, in := w.entries[id]; !in {
					continue
				}
				w.m.Lock()
				delete(w.entries, id)
				w.m.Unlock()
			} else {
				w.m.Lock()
				w.entries[id] = el
				w.m.Unlock()
			}
			atomic.AddUint64(&w.version, 1)
			lastUpdate = time.Now()
		case t := <-ticker.C:
			if t.Sub(lastUpdate) < LIST_INTERVAL && t.Sub(lastRefresh) < REFRESH_INTERVAL {
				continue
			}
			lastUpdate = t
			lastRefresh = t
			list, err := w.client.CoreV1().Nodes().List(context.TODO(), metav1.ListOptions{})
			if err != nil {
				log.Warningf("call Nodes list failed: %v", err)
				continue
			}
			// 检查内存和List API查询结果是否一致
			if len(w.entries) == len(list.Items) {
				identical := true
				for _, item := range list.Items {
					if _, in := w.entries[string(item.ObjectMeta.UID)]; !in {
						identical = false
						break
					}
				}
				if identical {
					continue
				}
			}
			log.Debugf("reload %s data", "Nodes")
			w.m.Lock()
			w.entries = make(map[string]*corev1.Node)
			for i, item := range list.Items {
				w.entries[string(item.ObjectMeta.UID)] = &list.Items[i]
			}
			w.m.Unlock()
			atomic.AddUint64(&w.version, 1)
		}
	}
	ticker.Stop()
	log.Info("Nodes watcher stopped")
}

func StartCoreV1NodeWatcher(ctx context.Context, client *WatcherClient, namespace string) (Watcher, error) {
	w := &CoreV1NodeWatcher{
		ctx: ctx,

		client: client.kubernetes,

		entries:   make(map[string]*corev1.Node),
		namespace: namespace,
	}
	go w.run()
	return w, nil
}

/*
 * K8s同步watcher
 *     每一个watcher是一个单独的goroutine，由两个channel
 *     发过来的消息触发进行工作。其一是k8s api的watch消息，
 *     当监控的对象发生改变时，channel会收到事件，watcher
 *     只关注add和delete；另一个channel是每隔10分钟的tick，
 *     当watcher 10分钟内没有收到监控对象的添加删除事件时，
 *     会直接调用k8s list api拿到所有监控资源，和内存数据
 *     进行比对。此外，当API watcher退出时，ctx会自动关闭，
 *     watcher也会退出。
 */
type CoreV1NamespaceWatcher struct {
	ctx       context.Context
	client    *kubernetes.Clientset
	namespace string

	m       sync.RWMutex
	entries map[string]*corev1.Namespace
	version uint64

	hasError uint32
	errorMsg atomic.Value
}

func (w *CoreV1NamespaceWatcher) Type() string {
	return "NamespaceWatcher"
}

func (w *CoreV1NamespaceWatcher) Version() uint64 {
	return atomic.LoadUint64(&w.version)
}

func (w *CoreV1NamespaceWatcher) Error() string {
	if atomic.LoadUint32(&w.hasError) == 0 {
		return ""
	}
	atomic.StoreUint32(&w.hasError, 0)
	return w.errorMsg.Load().(string)
}

func (w *CoreV1NamespaceWatcher) Entries() []runtime.Object {
	w.m.RLock()
	entries := make([]runtime.Object, 0, len(w.entries))
	for _, e := range w.entries {
		entries = append(entries, e)
	}
	w.m.RUnlock()
	return entries
}

func (w *CoreV1NamespaceWatcher) run() {
	var watcher watch.Interface
	var err error

	log.Info("Namespaces watcher starting")
PREPARE:
	for {
		select {
		case <-w.ctx.Done():
			log.Info("Namespaces watcher stopped")
			return
		default:
			watcher, err = w.client.CoreV1().Namespaces().Watch(w.ctx, metav1.ListOptions{})
			if err == nil {
				break PREPARE
			}
			errMsg := fmt.Sprintf("Namespaces watcher Watch failed: %v", err)
			log.Warning(errMsg)
			w.errorMsg.Store(errMsg)
			atomic.StoreUint32(&w.hasError, 1)
			time.Sleep(time.Minute)
		}
	}

	log.Info("Namespaces watcher started")
	ticker := time.NewTicker(LIST_INTERVAL)
	lastUpdate := time.Now()
	lastRefresh := time.Now()
LOOP:
	for {
		select {
		case <-w.ctx.Done():
			log.Info("Namespaces watcher stopped")
			break LOOP
		case ev, ok := <-watcher.ResultChan():
			if !ok {
				log.Debugf("Namespaces watcher try rewatch")
				newWatcher, err := w.client.CoreV1().Namespaces().Watch(w.ctx, metav1.ListOptions{})
				if err != nil {
					errMsg := fmt.Sprintf("Namespaces watcher Watch failed: %v", err)
					log.Warning(errMsg)
					w.errorMsg.Store(errMsg)
					atomic.StoreUint32(&w.hasError, 1)
					time.Sleep(time.Minute)
				} else {
					watcher = newWatcher
				}
				continue LOOP
			}
			if ev.Type == watch.Error {
				if to, ok := ev.Object.(*metav1.Status); ok {
					if strings.Contains(to.Message, "RST_STREAM") {
						// 正常的超时
						log.Debugf("Namespaces watcher timeout rewatch")
						continue
					}
				}
				log.Warningf("Namespaces watcher has error: %v", ev.Object)
				continue
			}
			if ev.Type != watch.Added && ev.Type != watch.Deleted && ev.Type != watch.Modified {
				continue
			}
			el, ok := ev.Object.(*corev1.Namespace)
			if !ok {
				continue
			}
			id := string(el.ObjectMeta.UID)
			// 只有删除时检查是否需要更新版本号，其余消息直接更新map内容
			if ev.Type == watch.Deleted {
				if _, in := w.entries[id]; !in {
					continue
				}
				w.m.Lock()
				delete(w.entries, id)
				w.m.Unlock()
			} else {
				w.m.Lock()
				w.entries[id] = el
				w.m.Unlock()
			}
			atomic.AddUint64(&w.version, 1)
			lastUpdate = time.Now()
		case t := <-ticker.C:
			if t.Sub(lastUpdate) < LIST_INTERVAL && t.Sub(lastRefresh) < REFRESH_INTERVAL {
				continue
			}
			lastUpdate = t
			lastRefresh = t
			list, err := w.client.CoreV1().Namespaces().List(context.TODO(), metav1.ListOptions{})
			if err != nil {
				log.Warningf("call Namespaces list failed: %v", err)
				continue
			}
			// 检查内存和List API查询结果是否一致
			if len(w.entries) == len(list.Items) {
				identical := true
				for _, item := range list.Items {
					if _, in := w.entries[string(item.ObjectMeta.UID)]; !in {
						identical = false
						break
					}
				}
				if identical {
					continue
				}
			}
			log.Debugf("reload %s data", "Namespaces")
			w.m.Lock()
			w.entries = make(map[string]*corev1.Namespace)
			for i, item := range list.Items {
				w.entries[string(item.ObjectMeta.UID)] = &list.Items[i]
			}
			w.m.Unlock()
			atomic.AddUint64(&w.version, 1)
		}
	}
	ticker.Stop()
	log.Info("Namespaces watcher stopped")
}

func StartCoreV1NamespaceWatcher(ctx context.Context, client *WatcherClient, namespace string) (Watcher, error) {
	w := &CoreV1NamespaceWatcher{
		ctx: ctx,

		client: client.kubernetes,

		entries:   make(map[string]*corev1.Namespace),
		namespace: namespace,
	}
	go w.run()
	return w, nil
}

/*
 * K8s同步watcher
 *     每一个watcher是一个单独的goroutine，由两个channel
 *     发过来的消息触发进行工作。其一是k8s api的watch消息，
 *     当监控的对象发生改变时，channel会收到事件，watcher
 *     只关注add和delete；另一个channel是每隔10分钟的tick，
 *     当watcher 10分钟内没有收到监控对象的添加删除事件时，
 *     会直接调用k8s list api拿到所有监控资源，和内存数据
 *     进行比对。此外，当API watcher退出时，ctx会自动关闭，
 *     watcher也会退出。
 */
type CoreV1ServiceWatcher struct {
	ctx       context.Context
	client    *kubernetes.Clientset
	namespace string

	m       sync.RWMutex
	entries map[string]*corev1.Service
	version uint64

	hasError uint32
	errorMsg atomic.Value
}

func (w *CoreV1ServiceWatcher) Type() string {
	return "ServiceWatcher"
}

func (w *CoreV1ServiceWatcher) Version() uint64 {
	return atomic.LoadUint64(&w.version)
}

func (w *CoreV1ServiceWatcher) Error() string {
	if atomic.LoadUint32(&w.hasError) == 0 {
		return ""
	}
	atomic.StoreUint32(&w.hasError, 0)
	return w.errorMsg.Load().(string)
}

func (w *CoreV1ServiceWatcher) Entries() []runtime.Object {
	w.m.RLock()
	entries := make([]runtime.Object, 0, len(w.entries))
	for _, e := range w.entries {
		entries = append(entries, e)
	}
	w.m.RUnlock()
	return entries
}

func (w *CoreV1ServiceWatcher) run() {
	var watcher watch.Interface
	var err error

	log.Info("Services watcher starting")
PREPARE:
	for {
		select {
		case <-w.ctx.Done():
			log.Info("Services watcher stopped")
			return
		default:
			watcher, err = w.client.CoreV1().Services(w.namespace).Watch(w.ctx, metav1.ListOptions{})
			if err == nil {
				break PREPARE
			}
			errMsg := fmt.Sprintf("Services watcher Watch failed: %v", err)
			log.Warning(errMsg)
			w.errorMsg.Store(errMsg)
			atomic.StoreUint32(&w.hasError, 1)
			time.Sleep(time.Minute)
		}
	}

	log.Info("Services watcher started")
	ticker := time.NewTicker(LIST_INTERVAL)
	lastUpdate := time.Now()
	lastRefresh := time.Now()
LOOP:
	for {
		select {
		case <-w.ctx.Done():
			log.Info("Services watcher stopped")
			break LOOP
		case ev, ok := <-watcher.ResultChan():
			if !ok {
				log.Debugf("Services watcher try rewatch")
				newWatcher, err := w.client.CoreV1().Services(w.namespace).Watch(w.ctx, metav1.ListOptions{})
				if err != nil {
					errMsg := fmt.Sprintf("Services watcher Watch failed: %v", err)
					log.Warning(errMsg)
					w.errorMsg.Store(errMsg)
					atomic.StoreUint32(&w.hasError, 1)
					time.Sleep(time.Minute)
				} else {
					watcher = newWatcher
				}
				continue LOOP
			}
			if ev.Type == watch.Error {
				if to, ok := ev.Object.(*metav1.Status); ok {
					if strings.Contains(to.Message, "RST_STREAM") {
						// 正常的超时
						log.Debugf("Services watcher timeout rewatch")
						continue
					}
				}
				log.Warningf("Services watcher has error: %v", ev.Object)
				continue
			}
			if ev.Type != watch.Added && ev.Type != watch.Deleted && ev.Type != watch.Modified {
				continue
			}
			el, ok := ev.Object.(*corev1.Service)
			if !ok {
				continue
			}
			id := string(el.ObjectMeta.UID)
			// 只有删除时检查是否需要更新版本号，其余消息直接更新map内容
			if ev.Type == watch.Deleted {
				if _, in := w.entries[id]; !in {
					continue
				}
				w.m.Lock()
				delete(w.entries, id)
				w.m.Unlock()
			} else {
				w.m.Lock()
				w.entries[id] = el
				w.m.Unlock()
			}
			atomic.AddUint64(&w.version, 1)
			lastUpdate = time.Now()
		case t := <-ticker.C:
			if t.Sub(lastUpdate) < LIST_INTERVAL && t.Sub(lastRefresh) < REFRESH_INTERVAL {
				continue
			}
			lastUpdate = t
			lastRefresh = t
			list, err := w.client.CoreV1().Services(w.namespace).List(context.TODO(), metav1.ListOptions{})
			if err != nil {
				log.Warningf("call Services list failed: %v", err)
				continue
			}
			// 检查内存和List API查询结果是否一致
			if len(w.entries) == len(list.Items) {
				identical := true
				for _, item := range list.Items {
					if _, in := w.entries[string(item.ObjectMeta.UID)]; !in {
						identical = false
						break
					}
				}
				if identical {
					continue
				}
			}
			log.Debugf("reload %s data", "Services")
			w.m.Lock()
			w.entries = make(map[string]*corev1.Service)
			for i, item := range list.Items {
				w.entries[string(item.ObjectMeta.UID)] = &list.Items[i]
			}
			w.m.Unlock()
			atomic.AddUint64(&w.version, 1)
		}
	}
	ticker.Stop()
	log.Info("Services watcher stopped")
}

func StartCoreV1ServiceWatcher(ctx context.Context, client *WatcherClient, namespace string) (Watcher, error) {
	w := &CoreV1ServiceWatcher{
		ctx: ctx,

		client: client.kubernetes,

		entries:   make(map[string]*corev1.Service),
		namespace: namespace,
	}
	go w.run()
	return w, nil
}

/*
 * K8s同步watcher
 *     每一个watcher是一个单独的goroutine，由两个channel
 *     发过来的消息触发进行工作。其一是k8s api的watch消息，
 *     当监控的对象发生改变时，channel会收到事件，watcher
 *     只关注add和delete；另一个channel是每隔10分钟的tick，
 *     当watcher 10分钟内没有收到监控对象的添加删除事件时，
 *     会直接调用k8s list api拿到所有监控资源，和内存数据
 *     进行比对。此外，当API watcher退出时，ctx会自动关闭，
 *     watcher也会退出。
 */
type CoreV1PodWatcher struct {
	ctx       context.Context
	client    *kubernetes.Clientset
	namespace string

	m       sync.RWMutex
	entries map[string]*corev1.Pod
	version uint64

	hasError uint32
	errorMsg atomic.Value
}

func (w *CoreV1PodWatcher) Type() string {
	return "PodWatcher"
}

func (w *CoreV1PodWatcher) Version() uint64 {
	return atomic.LoadUint64(&w.version)
}

func (w *CoreV1PodWatcher) Error() string {
	if atomic.LoadUint32(&w.hasError) == 0 {
		return ""
	}
	atomic.StoreUint32(&w.hasError, 0)
	return w.errorMsg.Load().(string)
}

func (w *CoreV1PodWatcher) Entries() []runtime.Object {
	w.m.RLock()
	entries := make([]runtime.Object, 0, len(w.entries))
	for _, e := range w.entries {
		entries = append(entries, e)
	}
	w.m.RUnlock()
	return entries
}

func (w *CoreV1PodWatcher) run() {
	var watcher watch.Interface
	var err error

	log.Info("Pods watcher starting")
PREPARE:
	for {
		select {
		case <-w.ctx.Done():
			log.Info("Pods watcher stopped")
			return
		default:
			watcher, err = w.client.CoreV1().Pods(w.namespace).Watch(w.ctx, metav1.ListOptions{})
			if err == nil {
				break PREPARE
			}
			errMsg := fmt.Sprintf("Pods watcher Watch failed: %v", err)
			log.Warning(errMsg)
			w.errorMsg.Store(errMsg)
			atomic.StoreUint32(&w.hasError, 1)
			time.Sleep(time.Minute)
		}
	}

	log.Info("Pods watcher started")
	ticker := time.NewTicker(LIST_INTERVAL)
	lastUpdate := time.Now()
	lastRefresh := time.Now()
LOOP:
	for {
		select {
		case <-w.ctx.Done():
			log.Info("Pods watcher stopped")
			break LOOP
		case ev, ok := <-watcher.ResultChan():
			if !ok {
				log.Debugf("Pods watcher try rewatch")
				newWatcher, err := w.client.CoreV1().Pods(w.namespace).Watch(w.ctx, metav1.ListOptions{})
				if err != nil {
					errMsg := fmt.Sprintf("Pods watcher Watch failed: %v", err)
					log.Warning(errMsg)
					w.errorMsg.Store(errMsg)
					atomic.StoreUint32(&w.hasError, 1)
					time.Sleep(time.Minute)
				} else {
					watcher = newWatcher
				}
				continue LOOP
			}
			if ev.Type == watch.Error {
				if to, ok := ev.Object.(*metav1.Status); ok {
					if strings.Contains(to.Message, "RST_STREAM") {
						// 正常的超时
						log.Debugf("Pods watcher timeout rewatch")
						continue
					}
				}
				log.Warningf("Pods watcher has error: %v", ev.Object)
				continue
			}
			if ev.Type != watch.Added && ev.Type != watch.Deleted && ev.Type != watch.Modified {
				continue
			}
			el, ok := ev.Object.(*corev1.Pod)
			if !ok {
				continue
			}
			id := string(el.ObjectMeta.UID)
			// 只有删除时检查是否需要更新版本号，其余消息直接更新map内容
			if ev.Type == watch.Deleted {
				if _, in := w.entries[id]; !in {
					continue
				}
				w.m.Lock()
				delete(w.entries, id)
				w.m.Unlock()
			} else {
				w.m.Lock()
				w.entries[id] = el
				w.m.Unlock()
			}
			atomic.AddUint64(&w.version, 1)
			lastUpdate = time.Now()
		case t := <-ticker.C:
			if t.Sub(lastUpdate) < LIST_INTERVAL && t.Sub(lastRefresh) < REFRESH_INTERVAL {
				continue
			}
			lastUpdate = t
			lastRefresh = t
			list, err := w.client.CoreV1().Pods(w.namespace).List(context.TODO(), metav1.ListOptions{})
			if err != nil {
				log.Warningf("call Pods list failed: %v", err)
				continue
			}
			// 检查内存和List API查询结果是否一致
			if len(w.entries) == len(list.Items) {
				identical := true
				for _, item := range list.Items {
					if _, in := w.entries[string(item.ObjectMeta.UID)]; !in {
						identical = false
						break
					}
				}
				if identical {
					continue
				}
			}
			log.Debugf("reload %s data", "Pods")
			w.m.Lock()
			w.entries = make(map[string]*corev1.Pod)
			for i, item := range list.Items {
				w.entries[string(item.ObjectMeta.UID)] = &list.Items[i]
			}
			w.m.Unlock()
			atomic.AddUint64(&w.version, 1)
		}
	}
	ticker.Stop()
	log.Info("Pods watcher stopped")
}

func StartCoreV1PodWatcher(ctx context.Context, client *WatcherClient, namespace string) (Watcher, error) {
	w := &CoreV1PodWatcher{
		ctx: ctx,

		client: client.kubernetes,

		entries:   make(map[string]*corev1.Pod),
		namespace: namespace,
	}
	go w.run()
	return w, nil
}

/*
 * K8s同步watcher
 *     每一个watcher是一个单独的goroutine，由两个channel
 *     发过来的消息触发进行工作。其一是k8s api的watch消息，
 *     当监控的对象发生改变时，channel会收到事件，watcher
 *     只关注add和delete；另一个channel是每隔10分钟的tick，
 *     当watcher 10分钟内没有收到监控对象的添加删除事件时，
 *     会直接调用k8s list api拿到所有监控资源，和内存数据
 *     进行比对。此外，当API watcher退出时，ctx会自动关闭，
 *     watcher也会退出。
 */
type CoreV1ReplicationControllerWatcher struct {
	ctx       context.Context
	client    *kubernetes.Clientset
	namespace string

	m       sync.RWMutex
	entries map[string]*corev1.ReplicationController
	version uint64

	hasError uint32
	errorMsg atomic.Value
}

func (w *CoreV1ReplicationControllerWatcher) Type() string {
	return "ReplicationControllerWatcher"
}

func (w *CoreV1ReplicationControllerWatcher) Version() uint64 {
	return atomic.LoadUint64(&w.version)
}

func (w *CoreV1ReplicationControllerWatcher) Error() string {
	if atomic.LoadUint32(&w.hasError) == 0 {
		return ""
	}
	atomic.StoreUint32(&w.hasError, 0)
	return w.errorMsg.Load().(string)
}

func (w *CoreV1ReplicationControllerWatcher) Entries() []runtime.Object {
	w.m.RLock()
	entries := make([]runtime.Object, 0, len(w.entries))
	for _, e := range w.entries {
		entries = append(entries, e)
	}
	w.m.RUnlock()
	return entries
}

func (w *CoreV1ReplicationControllerWatcher) run() {
	var watcher watch.Interface
	var err error

	log.Info("ReplicationControllers watcher starting")
PREPARE:
	for {
		select {
		case <-w.ctx.Done():
			log.Info("ReplicationControllers watcher stopped")
			return
		default:
			watcher, err = w.client.CoreV1().ReplicationControllers(w.namespace).Watch(w.ctx, metav1.ListOptions{})
			if err == nil {
				break PREPARE
			}
			errMsg := fmt.Sprintf("ReplicationControllers watcher Watch failed: %v", err)
			log.Warning(errMsg)
			w.errorMsg.Store(errMsg)
			atomic.StoreUint32(&w.hasError, 1)
			time.Sleep(time.Minute)
		}
	}

	log.Info("ReplicationControllers watcher started")
	ticker := time.NewTicker(LIST_INTERVAL)
	lastUpdate := time.Now()
	lastRefresh := time.Now()
LOOP:
	for {
		select {
		case <-w.ctx.Done():
			log.Info("ReplicationControllers watcher stopped")
			break LOOP
		case ev, ok := <-watcher.ResultChan():
			if !ok {
				log.Debugf("ReplicationControllers watcher try rewatch")
				newWatcher, err := w.client.CoreV1().ReplicationControllers(w.namespace).Watch(w.ctx, metav1.ListOptions{})
				if err != nil {
					errMsg := fmt.Sprintf("ReplicationControllers watcher Watch failed: %v", err)
					log.Warning(errMsg)
					w.errorMsg.Store(errMsg)
					atomic.StoreUint32(&w.hasError, 1)
					time.Sleep(time.Minute)
				} else {
					watcher = newWatcher
				}
				continue LOOP
			}
			if ev.Type == watch.Error {
				if to, ok := ev.Object.(*metav1.Status); ok {
					if strings.Contains(to.Message, "RST_STREAM") {
						// 正常的超时
						log.Debugf("ReplicationControllers watcher timeout rewatch")
						continue
					}
				}
				log.Warningf("ReplicationControllers watcher has error: %v", ev.Object)
				continue
			}
			if ev.Type != watch.Added && ev.Type != watch.Deleted && ev.Type != watch.Modified {
				continue
			}
			el, ok := ev.Object.(*corev1.ReplicationController)
			if !ok {
				continue
			}
			id := string(el.ObjectMeta.UID)
			// 只有删除时检查是否需要更新版本号，其余消息直接更新map内容
			if ev.Type == watch.Deleted {
				if _, in := w.entries[id]; !in {
					continue
				}
				w.m.Lock()
				delete(w.entries, id)
				w.m.Unlock()
			} else {
				w.m.Lock()
				w.entries[id] = el
				w.m.Unlock()
			}
			atomic.AddUint64(&w.version, 1)
			lastUpdate = time.Now()
		case t := <-ticker.C:
			if t.Sub(lastUpdate) < LIST_INTERVAL && t.Sub(lastRefresh) < REFRESH_INTERVAL {
				continue
			}
			lastUpdate = t
			lastRefresh = t
			list, err := w.client.CoreV1().ReplicationControllers(w.namespace).List(context.TODO(), metav1.ListOptions{})
			if err != nil {
				log.Warningf("call ReplicationControllers list failed: %v", err)
				continue
			}
			// 检查内存和List API查询结果是否一致
			if len(w.entries) == len(list.Items) {
				identical := true
				for _, item := range list.Items {
					if _, in := w.entries[string(item.ObjectMeta.UID)]; !in {
						identical = false
						break
					}
				}
				if identical {
					continue
				}
			}
			log.Debugf("reload %s data", "ReplicationControllers")
			w.m.Lock()
			w.entries = make(map[string]*corev1.ReplicationController)
			for i, item := range list.Items {
				w.entries[string(item.ObjectMeta.UID)] = &list.Items[i]
			}
			w.m.Unlock()
			atomic.AddUint64(&w.version, 1)
		}
	}
	ticker.Stop()
	log.Info("ReplicationControllers watcher stopped")
}

func StartCoreV1ReplicationControllerWatcher(ctx context.Context, client *WatcherClient, namespace string) (Watcher, error) {
	w := &CoreV1ReplicationControllerWatcher{
		ctx: ctx,

		client: client.kubernetes,

		entries:   make(map[string]*corev1.ReplicationController),
		namespace: namespace,
	}
	go w.run()
	return w, nil
}

/*
 * K8s同步watcher
 *     每一个watcher是一个单独的goroutine，由两个channel
 *     发过来的消息触发进行工作。其一是k8s api的watch消息，
 *     当监控的对象发生改变时，channel会收到事件，watcher
 *     只关注add和delete；另一个channel是每隔10分钟的tick，
 *     当watcher 10分钟内没有收到监控对象的添加删除事件时，
 *     会直接调用k8s list api拿到所有监控资源，和内存数据
 *     进行比对。此外，当API watcher退出时，ctx会自动关闭，
 *     watcher也会退出。
 */
type CoreV1EndpointsWatcher struct {
	ctx       context.Context
	client    *kubernetes.Clientset
	namespace string

	m       sync.RWMutex
	entries map[string]*corev1.Endpoints
	version uint64

	hasError uint32
	errorMsg atomic.Value
}

func (w *CoreV1EndpointsWatcher) Type() string {
	return "EndpointsWatcher"
}

func (w *CoreV1EndpointsWatcher) Version() uint64 {
	return atomic.LoadUint64(&w.version)
}

func (w *CoreV1EndpointsWatcher) Error() string {
	if atomic.LoadUint32(&w.hasError) == 0 {
		return ""
	}
	atomic.StoreUint32(&w.hasError, 0)
	return w.errorMsg.Load().(string)
}

func (w *CoreV1EndpointsWatcher) Entries() []runtime.Object {
	w.m.RLock()
	entries := make([]runtime.Object, 0, len(w.entries))
	for _, e := range w.entries {
		entries = append(entries, e)
	}
	w.m.RUnlock()
	return entries
}

func (w *CoreV1EndpointsWatcher) run() {
	var watcher watch.Interface
	var err error

	log.Info("Endpoints watcher starting")
PREPARE:
	for {
		select {
		case <-w.ctx.Done():
			log.Info("Endpoints watcher stopped")
			return
		default:
			watcher, err = w.client.CoreV1().Endpoints(w.namespace).Watch(w.ctx, metav1.ListOptions{})
			if err == nil {
				break PREPARE
			}
			errMsg := fmt.Sprintf("Endpoints watcher Watch failed: %v", err)
			log.Warning(errMsg)
			w.errorMsg.Store(errMsg)
			atomic.StoreUint32(&w.hasError, 1)
			time.Sleep(time.Minute)
		}
	}

	log.Info("Endpoints watcher started")
	ticker := time.NewTicker(LIST_INTERVAL)
	lastUpdate := time.Now()
	lastRefresh := time.Now()
LOOP:
	for {
		select {
		case <-w.ctx.Done():
			log.Info("Endpoints watcher stopped")
			break LOOP
		case ev, ok := <-watcher.ResultChan():
			if !ok {
				log.Debugf("Endpoints watcher try rewatch")
				newWatcher, err := w.client.CoreV1().Endpoints(w.namespace).Watch(w.ctx, metav1.ListOptions{})
				if err != nil {
					errMsg := fmt.Sprintf("Endpoints watcher Watch failed: %v", err)
					log.Warning(errMsg)
					w.errorMsg.Store(errMsg)
					atomic.StoreUint32(&w.hasError, 1)
					time.Sleep(time.Minute)
				} else {
					watcher = newWatcher
				}
				continue LOOP
			}
			if ev.Type == watch.Error {
				if to, ok := ev.Object.(*metav1.Status); ok {
					if strings.Contains(to.Message, "RST_STREAM") {
						// 正常的超时
						log.Debugf("Endpoints watcher timeout rewatch")
						continue
					}
				}
				log.Warningf("Endpoints watcher has error: %v", ev.Object)
				continue
			}
			if ev.Type != watch.Added && ev.Type != watch.Deleted && ev.Type != watch.Modified {
				continue
			}
			el, ok := ev.Object.(*corev1.Endpoints)
			if !ok {
				continue
			}
			id := string(el.ObjectMeta.UID)
			// 只有删除时检查是否需要更新版本号，其余消息直接更新map内容
			if ev.Type == watch.Deleted {
				if _, in := w.entries[id]; !in {
					continue
				}
				w.m.Lock()
				delete(w.entries, id)
				w.m.Unlock()
			} else {
				w.m.Lock()
				w.entries[id] = el
				w.m.Unlock()
			}
			atomic.AddUint64(&w.version, 1)
			lastUpdate = time.Now()
		case t := <-ticker.C:
			if t.Sub(lastUpdate) < LIST_INTERVAL && t.Sub(lastRefresh) < REFRESH_INTERVAL {
				continue
			}
			lastUpdate = t
			lastRefresh = t
			list, err := w.client.CoreV1().Endpoints(w.namespace).List(context.TODO(), metav1.ListOptions{})
			if err != nil {
				log.Warningf("call Endpoints list failed: %v", err)
				continue
			}
			// 检查内存和List API查询结果是否一致
			if len(w.entries) == len(list.Items) {
				identical := true
				for _, item := range list.Items {
					if _, in := w.entries[string(item.ObjectMeta.UID)]; !in {
						identical = false
						break
					}
				}
				if identical {
					continue
				}
			}
			log.Debugf("reload %s data", "Endpoints")
			w.m.Lock()
			w.entries = make(map[string]*corev1.Endpoints)
			for i, item := range list.Items {
				w.entries[string(item.ObjectMeta.UID)] = &list.Items[i]
			}
			w.m.Unlock()
			atomic.AddUint64(&w.version, 1)
		}
	}
	ticker.Stop()
	log.Info("Endpoints watcher stopped")
}

func StartCoreV1EndpointsWatcher(ctx context.Context, client *WatcherClient, namespace string) (Watcher, error) {
	w := &CoreV1EndpointsWatcher{
		ctx: ctx,

		client: client.kubernetes,

		entries:   make(map[string]*corev1.Endpoints),
		namespace: namespace,
	}
	go w.run()
	return w, nil
}

/*
 * K8s同步watcher
 *     每一个watcher是一个单独的goroutine，由两个channel
 *     发过来的消息触发进行工作。其一是k8s api的watch消息，
 *     当监控的对象发生改变时，channel会收到事件，watcher
 *     只关注add和delete；另一个channel是每隔10分钟的tick，
 *     当watcher 10分钟内没有收到监控对象的添加删除事件时，
 *     会直接调用k8s list api拿到所有监控资源，和内存数据
 *     进行比对。此外，当API watcher退出时，ctx会自动关闭，
 *     watcher也会退出。
 */
type AppsV1DeploymentWatcher struct {
	ctx       context.Context
	client    *kubernetes.Clientset
	namespace string

	m       sync.RWMutex
	entries map[string]*appsv1.Deployment
	version uint64

	hasError uint32
	errorMsg atomic.Value
}

func (w *AppsV1DeploymentWatcher) Type() string {
	return "DeploymentWatcher"
}

func (w *AppsV1DeploymentWatcher) Version() uint64 {
	return atomic.LoadUint64(&w.version)
}

func (w *AppsV1DeploymentWatcher) Error() string {
	if atomic.LoadUint32(&w.hasError) == 0 {
		return ""
	}
	atomic.StoreUint32(&w.hasError, 0)
	return w.errorMsg.Load().(string)
}

func (w *AppsV1DeploymentWatcher) Entries() []runtime.Object {
	w.m.RLock()
	entries := make([]runtime.Object, 0, len(w.entries))
	for _, e := range w.entries {
		entries = append(entries, e)
	}
	w.m.RUnlock()
	return entries
}

func (w *AppsV1DeploymentWatcher) run() {
	var watcher watch.Interface
	var err error

	log.Info("Deployments watcher starting")
PREPARE:
	for {
		select {
		case <-w.ctx.Done():
			log.Info("Deployments watcher stopped")
			return
		default:
			watcher, err = w.client.AppsV1().Deployments(w.namespace).Watch(w.ctx, metav1.ListOptions{})
			if err == nil {
				break PREPARE
			}
			errMsg := fmt.Sprintf("Deployments watcher Watch failed: %v", err)
			log.Warning(errMsg)
			w.errorMsg.Store(errMsg)
			atomic.StoreUint32(&w.hasError, 1)
			time.Sleep(time.Minute)
		}
	}

	log.Info("Deployments watcher started")
	ticker := time.NewTicker(LIST_INTERVAL)
	lastUpdate := time.Now()
	lastRefresh := time.Now()
LOOP:
	for {
		select {
		case <-w.ctx.Done():
			log.Info("Deployments watcher stopped")
			break LOOP
		case ev, ok := <-watcher.ResultChan():
			if !ok {
				log.Debugf("Deployments watcher try rewatch")
				newWatcher, err := w.client.AppsV1().Deployments(w.namespace).Watch(w.ctx, metav1.ListOptions{})
				if err != nil {
					errMsg := fmt.Sprintf("Deployments watcher Watch failed: %v", err)
					log.Warning(errMsg)
					w.errorMsg.Store(errMsg)
					atomic.StoreUint32(&w.hasError, 1)
					time.Sleep(time.Minute)
				} else {
					watcher = newWatcher
				}
				continue LOOP
			}
			if ev.Type == watch.Error {
				if to, ok := ev.Object.(*metav1.Status); ok {
					if strings.Contains(to.Message, "RST_STREAM") {
						// 正常的超时
						log.Debugf("Deployments watcher timeout rewatch")
						continue
					}
				}
				log.Warningf("Deployments watcher has error: %v", ev.Object)
				continue
			}
			if ev.Type != watch.Added && ev.Type != watch.Deleted && ev.Type != watch.Modified {
				continue
			}
			el, ok := ev.Object.(*appsv1.Deployment)
			if !ok {
				continue
			}
			id := string(el.ObjectMeta.UID)
			// 只有删除时检查是否需要更新版本号，其余消息直接更新map内容
			if ev.Type == watch.Deleted {
				if _, in := w.entries[id]; !in {
					continue
				}
				w.m.Lock()
				delete(w.entries, id)
				w.m.Unlock()
			} else {
				w.m.Lock()
				w.entries[id] = el
				w.m.Unlock()
			}
			atomic.AddUint64(&w.version, 1)
			lastUpdate = time.Now()
		case t := <-ticker.C:
			if t.Sub(lastUpdate) < LIST_INTERVAL && t.Sub(lastRefresh) < REFRESH_INTERVAL {
				continue
			}
			lastUpdate = t
			lastRefresh = t
			list, err := w.client.AppsV1().Deployments(w.namespace).List(context.TODO(), metav1.ListOptions{})
			if err != nil {
				log.Warningf("call Deployments list failed: %v", err)
				continue
			}
			// 检查内存和List API查询结果是否一致
			if len(w.entries) == len(list.Items) {
				identical := true
				for _, item := range list.Items {
					if _, in := w.entries[string(item.ObjectMeta.UID)]; !in {
						identical = false
						break
					}
				}
				if identical {
					continue
				}
			}
			log.Debugf("reload %s data", "Deployments")
			w.m.Lock()
			w.entries = make(map[string]*appsv1.Deployment)
			for i, item := range list.Items {
				w.entries[string(item.ObjectMeta.UID)] = &list.Items[i]
			}
			w.m.Unlock()
			atomic.AddUint64(&w.version, 1)
		}
	}
	ticker.Stop()
	log.Info("Deployments watcher stopped")
}

func StartAppsV1DeploymentWatcher(ctx context.Context, client *WatcherClient, namespace string) (Watcher, error) {
	w := &AppsV1DeploymentWatcher{
		ctx: ctx,

		client: client.kubernetes,

		entries:   make(map[string]*appsv1.Deployment),
		namespace: namespace,
	}
	go w.run()
	return w, nil
}

/*
 * K8s同步watcher
 *     每一个watcher是一个单独的goroutine，由两个channel
 *     发过来的消息触发进行工作。其一是k8s api的watch消息，
 *     当监控的对象发生改变时，channel会收到事件，watcher
 *     只关注add和delete；另一个channel是每隔10分钟的tick，
 *     当watcher 10分钟内没有收到监控对象的添加删除事件时，
 *     会直接调用k8s list api拿到所有监控资源，和内存数据
 *     进行比对。此外，当API watcher退出时，ctx会自动关闭，
 *     watcher也会退出。
 */
type AppsV1StatefulSetWatcher struct {
	ctx       context.Context
	client    *kubernetes.Clientset
	namespace string

	m       sync.RWMutex
	entries map[string]*appsv1.StatefulSet
	version uint64

	hasError uint32
	errorMsg atomic.Value
}

func (w *AppsV1StatefulSetWatcher) Type() string {
	return "StatefulSetWatcher"
}

func (w *AppsV1StatefulSetWatcher) Version() uint64 {
	return atomic.LoadUint64(&w.version)
}

func (w *AppsV1StatefulSetWatcher) Error() string {
	if atomic.LoadUint32(&w.hasError) == 0 {
		return ""
	}
	atomic.StoreUint32(&w.hasError, 0)
	return w.errorMsg.Load().(string)
}

func (w *AppsV1StatefulSetWatcher) Entries() []runtime.Object {
	w.m.RLock()
	entries := make([]runtime.Object, 0, len(w.entries))
	for _, e := range w.entries {
		entries = append(entries, e)
	}
	w.m.RUnlock()
	return entries
}

func (w *AppsV1StatefulSetWatcher) run() {
	var watcher watch.Interface
	var err error

	log.Info("StatefulSets watcher starting")
PREPARE:
	for {
		select {
		case <-w.ctx.Done():
			log.Info("StatefulSets watcher stopped")
			return
		default:
			watcher, err = w.client.AppsV1().StatefulSets(w.namespace).Watch(w.ctx, metav1.ListOptions{})
			if err == nil {
				break PREPARE
			}
			errMsg := fmt.Sprintf("StatefulSets watcher Watch failed: %v", err)
			log.Warning(errMsg)
			w.errorMsg.Store(errMsg)
			atomic.StoreUint32(&w.hasError, 1)
			time.Sleep(time.Minute)
		}
	}

	log.Info("StatefulSets watcher started")
	ticker := time.NewTicker(LIST_INTERVAL)
	lastUpdate := time.Now()
	lastRefresh := time.Now()
LOOP:
	for {
		select {
		case <-w.ctx.Done():
			log.Info("StatefulSets watcher stopped")
			break LOOP
		case ev, ok := <-watcher.ResultChan():
			if !ok {
				log.Debugf("StatefulSets watcher try rewatch")
				newWatcher, err := w.client.AppsV1().StatefulSets(w.namespace).Watch(w.ctx, metav1.ListOptions{})
				if err != nil {
					errMsg := fmt.Sprintf("StatefulSets watcher Watch failed: %v", err)
					log.Warning(errMsg)
					w.errorMsg.Store(errMsg)
					atomic.StoreUint32(&w.hasError, 1)
					time.Sleep(time.Minute)
				} else {
					watcher = newWatcher
				}
				continue LOOP
			}
			if ev.Type == watch.Error {
				if to, ok := ev.Object.(*metav1.Status); ok {
					if strings.Contains(to.Message, "RST_STREAM") {
						// 正常的超时
						log.Debugf("StatefulSets watcher timeout rewatch")
						continue
					}
				}
				log.Warningf("StatefulSets watcher has error: %v", ev.Object)
				continue
			}
			if ev.Type != watch.Added && ev.Type != watch.Deleted && ev.Type != watch.Modified {
				continue
			}
			el, ok := ev.Object.(*appsv1.StatefulSet)
			if !ok {
				continue
			}
			id := string(el.ObjectMeta.UID)
			// 只有删除时检查是否需要更新版本号，其余消息直接更新map内容
			if ev.Type == watch.Deleted {
				if _, in := w.entries[id]; !in {
					continue
				}
				w.m.Lock()
				delete(w.entries, id)
				w.m.Unlock()
			} else {
				w.m.Lock()
				w.entries[id] = el
				w.m.Unlock()
			}
			atomic.AddUint64(&w.version, 1)
			lastUpdate = time.Now()
		case t := <-ticker.C:
			if t.Sub(lastUpdate) < LIST_INTERVAL && t.Sub(lastRefresh) < REFRESH_INTERVAL {
				continue
			}
			lastUpdate = t
			lastRefresh = t
			list, err := w.client.AppsV1().StatefulSets(w.namespace).List(context.TODO(), metav1.ListOptions{})
			if err != nil {
				log.Warningf("call StatefulSets list failed: %v", err)
				continue
			}
			// 检查内存和List API查询结果是否一致
			if len(w.entries) == len(list.Items) {
				identical := true
				for _, item := range list.Items {
					if _, in := w.entries[string(item.ObjectMeta.UID)]; !in {
						identical = false
						break
					}
				}
				if identical {
					continue
				}
			}
			log.Debugf("reload %s data", "StatefulSets")
			w.m.Lock()
			w.entries = make(map[string]*appsv1.StatefulSet)
			for i, item := range list.Items {
				w.entries[string(item.ObjectMeta.UID)] = &list.Items[i]
			}
			w.m.Unlock()
			atomic.AddUint64(&w.version, 1)
		}
	}
	ticker.Stop()
	log.Info("StatefulSets watcher stopped")
}

func StartAppsV1StatefulSetWatcher(ctx context.Context, client *WatcherClient, namespace string) (Watcher, error) {
	w := &AppsV1StatefulSetWatcher{
		ctx: ctx,

		client: client.kubernetes,

		entries:   make(map[string]*appsv1.StatefulSet),
		namespace: namespace,
	}
	go w.run()
	return w, nil
}

/*
 * K8s同步watcher
 *     每一个watcher是一个单独的goroutine，由两个channel
 *     发过来的消息触发进行工作。其一是k8s api的watch消息，
 *     当监控的对象发生改变时，channel会收到事件，watcher
 *     只关注add和delete；另一个channel是每隔10分钟的tick，
 *     当watcher 10分钟内没有收到监控对象的添加删除事件时，
 *     会直接调用k8s list api拿到所有监控资源，和内存数据
 *     进行比对。此外，当API watcher退出时，ctx会自动关闭，
 *     watcher也会退出。
 */
type AppsV1DaemonSetWatcher struct {
	ctx       context.Context
	client    *kubernetes.Clientset
	namespace string

	m       sync.RWMutex
	entries map[string]*appsv1.DaemonSet
	version uint64

	hasError uint32
	errorMsg atomic.Value
}

func (w *AppsV1DaemonSetWatcher) Type() string {
	return "DaemonSetWatcher"
}

func (w *AppsV1DaemonSetWatcher) Version() uint64 {
	return atomic.LoadUint64(&w.version)
}

func (w *AppsV1DaemonSetWatcher) Error() string {
	if atomic.LoadUint32(&w.hasError) == 0 {
		return ""
	}
	atomic.StoreUint32(&w.hasError, 0)
	return w.errorMsg.Load().(string)
}

func (w *AppsV1DaemonSetWatcher) Entries() []runtime.Object {
	w.m.RLock()
	entries := make([]runtime.Object, 0, len(w.entries))
	for _, e := range w.entries {
		entries = append(entries, e)
	}
	w.m.RUnlock()
	return entries
}

func (w *AppsV1DaemonSetWatcher) run() {
	var watcher watch.Interface
	var err error

	log.Info("DaemonSets watcher starting")
PREPARE:
	for {
		select {
		case <-w.ctx.Done():
			log.Info("DaemonSets watcher stopped")
			return
		default:
			watcher, err = w.client.AppsV1().DaemonSets(w.namespace).Watch(w.ctx, metav1.ListOptions{})
			if err == nil {
				break PREPARE
			}
			errMsg := fmt.Sprintf("DaemonSets watcher Watch failed: %v", err)
			log.Warning(errMsg)
			w.errorMsg.Store(errMsg)
			atomic.StoreUint32(&w.hasError, 1)
			time.Sleep(time.Minute)
		}
	}

	log.Info("DaemonSets watcher started")
	ticker := time.NewTicker(LIST_INTERVAL)
	lastUpdate := time.Now()
	lastRefresh := time.Now()
LOOP:
	for {
		select {
		case <-w.ctx.Done():
			log.Info("DaemonSets watcher stopped")
			break LOOP
		case ev, ok := <-watcher.ResultChan():
			if !ok {
				log.Debugf("DaemonSets watcher try rewatch")
				newWatcher, err := w.client.AppsV1().DaemonSets(w.namespace).Watch(w.ctx, metav1.ListOptions{})
				if err != nil {
					errMsg := fmt.Sprintf("DaemonSets watcher Watch failed: %v", err)
					log.Warning(errMsg)
					w.errorMsg.Store(errMsg)
					atomic.StoreUint32(&w.hasError, 1)
					time.Sleep(time.Minute)
				} else {
					watcher = newWatcher
				}
				continue LOOP
			}
			if ev.Type == watch.Error {
				if to, ok := ev.Object.(*metav1.Status); ok {
					if strings.Contains(to.Message, "RST_STREAM") {
						// 正常的超时
						log.Debugf("DaemonSets watcher timeout rewatch")
						continue
					}
				}
				log.Warningf("DaemonSets watcher has error: %v", ev.Object)
				continue
			}
			if ev.Type != watch.Added && ev.Type != watch.Deleted && ev.Type != watch.Modified {
				continue
			}
			el, ok := ev.Object.(*appsv1.DaemonSet)
			if !ok {
				continue
			}
			id := string(el.ObjectMeta.UID)
			// 只有删除时检查是否需要更新版本号，其余消息直接更新map内容
			if ev.Type == watch.Deleted {
				if _, in := w.entries[id]; !in {
					continue
				}
				w.m.Lock()
				delete(w.entries, id)
				w.m.Unlock()
			} else {
				w.m.Lock()
				w.entries[id] = el
				w.m.Unlock()
			}
			atomic.AddUint64(&w.version, 1)
			lastUpdate = time.Now()
		case t := <-ticker.C:
			if t.Sub(lastUpdate) < LIST_INTERVAL && t.Sub(lastRefresh) < REFRESH_INTERVAL {
				continue
			}
			lastUpdate = t
			lastRefresh = t
			list, err := w.client.AppsV1().DaemonSets(w.namespace).List(context.TODO(), metav1.ListOptions{})
			if err != nil {
				log.Warningf("call DaemonSets list failed: %v", err)
				continue
			}
			// 检查内存和List API查询结果是否一致
			if len(w.entries) == len(list.Items) {
				identical := true
				for _, item := range list.Items {
					if _, in := w.entries[string(item.ObjectMeta.UID)]; !in {
						identical = false
						break
					}
				}
				if identical {
					continue
				}
			}
			log.Debugf("reload %s data", "DaemonSets")
			w.m.Lock()
			w.entries = make(map[string]*appsv1.DaemonSet)
			for i, item := range list.Items {
				w.entries[string(item.ObjectMeta.UID)] = &list.Items[i]
			}
			w.m.Unlock()
			atomic.AddUint64(&w.version, 1)
		}
	}
	ticker.Stop()
	log.Info("DaemonSets watcher stopped")
}

func StartAppsV1DaemonSetWatcher(ctx context.Context, client *WatcherClient, namespace string) (Watcher, error) {
	w := &AppsV1DaemonSetWatcher{
		ctx: ctx,

		client: client.kubernetes,

		entries:   make(map[string]*appsv1.DaemonSet),
		namespace: namespace,
	}
	go w.run()
	return w, nil
}

/*
 * K8s同步watcher
 *     每一个watcher是一个单独的goroutine，由两个channel
 *     发过来的消息触发进行工作。其一是k8s api的watch消息，
 *     当监控的对象发生改变时，channel会收到事件，watcher
 *     只关注add和delete；另一个channel是每隔10分钟的tick，
 *     当watcher 10分钟内没有收到监控对象的添加删除事件时，
 *     会直接调用k8s list api拿到所有监控资源，和内存数据
 *     进行比对。此外，当API watcher退出时，ctx会自动关闭，
 *     watcher也会退出。
 */
type AppsV1ReplicaSetWatcher struct {
	ctx       context.Context
	client    *kubernetes.Clientset
	namespace string

	m       sync.RWMutex
	entries map[string]*appsv1.ReplicaSet
	version uint64

	hasError uint32
	errorMsg atomic.Value
}

func (w *AppsV1ReplicaSetWatcher) Type() string {
	return "ReplicaSetWatcher"
}

func (w *AppsV1ReplicaSetWatcher) Version() uint64 {
	return atomic.LoadUint64(&w.version)
}

func (w *AppsV1ReplicaSetWatcher) Error() string {
	if atomic.LoadUint32(&w.hasError) == 0 {
		return ""
	}
	atomic.StoreUint32(&w.hasError, 0)
	return w.errorMsg.Load().(string)
}

func (w *AppsV1ReplicaSetWatcher) Entries() []runtime.Object {
	w.m.RLock()
	entries := make([]runtime.Object, 0, len(w.entries))
	for _, e := range w.entries {
		entries = append(entries, e)
	}
	w.m.RUnlock()
	return entries
}

func (w *AppsV1ReplicaSetWatcher) run() {
	var watcher watch.Interface
	var err error

	log.Info("ReplicaSets watcher starting")
PREPARE:
	for {
		select {
		case <-w.ctx.Done():
			log.Info("ReplicaSets watcher stopped")
			return
		default:
			watcher, err = w.client.AppsV1().ReplicaSets(w.namespace).Watch(w.ctx, metav1.ListOptions{})
			if err == nil {
				break PREPARE
			}
			errMsg := fmt.Sprintf("ReplicaSets watcher Watch failed: %v", err)
			log.Warning(errMsg)
			w.errorMsg.Store(errMsg)
			atomic.StoreUint32(&w.hasError, 1)
			time.Sleep(time.Minute)
		}
	}

	log.Info("ReplicaSets watcher started")
	ticker := time.NewTicker(LIST_INTERVAL)
	lastUpdate := time.Now()
	lastRefresh := time.Now()
LOOP:
	for {
		select {
		case <-w.ctx.Done():
			log.Info("ReplicaSets watcher stopped")
			break LOOP
		case ev, ok := <-watcher.ResultChan():
			if !ok {
				log.Debugf("ReplicaSets watcher try rewatch")
				newWatcher, err := w.client.AppsV1().ReplicaSets(w.namespace).Watch(w.ctx, metav1.ListOptions{})
				if err != nil {
					errMsg := fmt.Sprintf("ReplicaSets watcher Watch failed: %v", err)
					log.Warning(errMsg)
					w.errorMsg.Store(errMsg)
					atomic.StoreUint32(&w.hasError, 1)
					time.Sleep(time.Minute)
				} else {
					watcher = newWatcher
				}
				continue LOOP
			}
			if ev.Type == watch.Error {
				if to, ok := ev.Object.(*metav1.Status); ok {
					if strings.Contains(to.Message, "RST_STREAM") {
						// 正常的超时
						log.Debugf("ReplicaSets watcher timeout rewatch")
						continue
					}
				}
				log.Warningf("ReplicaSets watcher has error: %v", ev.Object)
				continue
			}
			if ev.Type != watch.Added && ev.Type != watch.Deleted && ev.Type != watch.Modified {
				continue
			}
			el, ok := ev.Object.(*appsv1.ReplicaSet)
			if !ok {
				continue
			}
			id := string(el.ObjectMeta.UID)
			// 只有删除时检查是否需要更新版本号，其余消息直接更新map内容
			if ev.Type == watch.Deleted {
				if _, in := w.entries[id]; !in {
					continue
				}
				w.m.Lock()
				delete(w.entries, id)
				w.m.Unlock()
			} else {
				w.m.Lock()
				w.entries[id] = el
				w.m.Unlock()
			}
			atomic.AddUint64(&w.version, 1)
			lastUpdate = time.Now()
		case t := <-ticker.C:
			if t.Sub(lastUpdate) < LIST_INTERVAL && t.Sub(lastRefresh) < REFRESH_INTERVAL {
				continue
			}
			lastUpdate = t
			lastRefresh = t
			list, err := w.client.AppsV1().ReplicaSets(w.namespace).List(context.TODO(), metav1.ListOptions{})
			if err != nil {
				log.Warningf("call ReplicaSets list failed: %v", err)
				continue
			}
			// 检查内存和List API查询结果是否一致
			if len(w.entries) == len(list.Items) {
				identical := true
				for _, item := range list.Items {
					if _, in := w.entries[string(item.ObjectMeta.UID)]; !in {
						identical = false
						break
					}
				}
				if identical {
					continue
				}
			}
			log.Debugf("reload %s data", "ReplicaSets")
			w.m.Lock()
			w.entries = make(map[string]*appsv1.ReplicaSet)
			for i, item := range list.Items {
				w.entries[string(item.ObjectMeta.UID)] = &list.Items[i]
			}
			w.m.Unlock()
			atomic.AddUint64(&w.version, 1)
		}
	}
	ticker.Stop()
	log.Info("ReplicaSets watcher stopped")
}

func StartAppsV1ReplicaSetWatcher(ctx context.Context, client *WatcherClient, namespace string) (Watcher, error) {
	w := &AppsV1ReplicaSetWatcher{
		ctx: ctx,

		client: client.kubernetes,

		entries:   make(map[string]*appsv1.ReplicaSet),
		namespace: namespace,
	}
	go w.run()
	return w, nil
}

/*
 * K8s同步watcher
 *     每一个watcher是一个单独的goroutine，由两个channel
 *     发过来的消息触发进行工作。其一是k8s api的watch消息，
 *     当监控的对象发生改变时，channel会收到事件，watcher
 *     只关注add和delete；另一个channel是每隔10分钟的tick，
 *     当watcher 10分钟内没有收到监控对象的添加删除事件时，
 *     会直接调用k8s list api拿到所有监控资源，和内存数据
 *     进行比对。此外，当API watcher退出时，ctx会自动关闭，
 *     watcher也会退出。
 */
type NetworkingV1IngressWatcher struct {
	ctx       context.Context
	client    *kubernetes.Clientset
	namespace string

	m       sync.RWMutex
	entries map[string]*networkingv1.Ingress
	version uint64

	hasError uint32
	errorMsg atomic.Value
}

func (w *NetworkingV1IngressWatcher) Type() string {
	return "IngressWatcher"
}

func (w *NetworkingV1IngressWatcher) Version() uint64 {
	return atomic.LoadUint64(&w.version)
}

func (w *NetworkingV1IngressWatcher) Error() string {
	if atomic.LoadUint32(&w.hasError) == 0 {
		return ""
	}
	atomic.StoreUint32(&w.hasError, 0)
	return w.errorMsg.Load().(string)
}

func (w *NetworkingV1IngressWatcher) Entries() []runtime.Object {
	w.m.RLock()
	entries := make([]runtime.Object, 0, len(w.entries))
	for _, e := range w.entries {
		entries = append(entries, e)
	}
	w.m.RUnlock()
	return entries
}

func (w *NetworkingV1IngressWatcher) run() {
	var watcher watch.Interface
	var err error

	log.Info("Ingresses watcher starting")
PREPARE:
	for {
		select {
		case <-w.ctx.Done():
			log.Info("Ingresses watcher stopped")
			return
		default:
			watcher, err = w.client.NetworkingV1().Ingresses(w.namespace).Watch(w.ctx, metav1.ListOptions{})
			if err == nil {
				break PREPARE
			}
			errMsg := fmt.Sprintf("Ingresses watcher Watch failed: %v", err)
			log.Warning(errMsg)
			w.errorMsg.Store(errMsg)
			atomic.StoreUint32(&w.hasError, 1)
			time.Sleep(time.Minute)
		}
	}

	log.Info("Ingresses watcher started")
	ticker := time.NewTicker(LIST_INTERVAL)
	lastUpdate := time.Now()
	lastRefresh := time.Now()
LOOP:
	for {
		select {
		case <-w.ctx.Done():
			log.Info("Ingresses watcher stopped")
			break LOOP
		case ev, ok := <-watcher.ResultChan():
			if !ok {
				log.Debugf("Ingresses watcher try rewatch")
				newWatcher, err := w.client.NetworkingV1().Ingresses(w.namespace).Watch(w.ctx, metav1.ListOptions{})
				if err != nil {
					errMsg := fmt.Sprintf("Ingresses watcher Watch failed: %v", err)
					log.Warning(errMsg)
					w.errorMsg.Store(errMsg)
					atomic.StoreUint32(&w.hasError, 1)
					time.Sleep(time.Minute)
				} else {
					watcher = newWatcher
				}
				continue LOOP
			}
			if ev.Type == watch.Error {
				if to, ok := ev.Object.(*metav1.Status); ok {
					if strings.Contains(to.Message, "RST_STREAM") {
						// 正常的超时
						log.Debugf("Ingresses watcher timeout rewatch")
						continue
					}
				}
				log.Warningf("Ingresses watcher has error: %v", ev.Object)
				continue
			}
			if ev.Type != watch.Added && ev.Type != watch.Deleted && ev.Type != watch.Modified {
				continue
			}
			el, ok := ev.Object.(*networkingv1.Ingress)
			if !ok {
				continue
			}
			id := string(el.ObjectMeta.UID)
			// 只有删除时检查是否需要更新版本号，其余消息直接更新map内容
			if ev.Type == watch.Deleted {
				if _, in := w.entries[id]; !in {
					continue
				}
				w.m.Lock()
				delete(w.entries, id)
				w.m.Unlock()
			} else {
				w.m.Lock()
				w.entries[id] = el
				w.m.Unlock()
			}
			atomic.AddUint64(&w.version, 1)
			lastUpdate = time.Now()
		case t := <-ticker.C:
			if t.Sub(lastUpdate) < LIST_INTERVAL && t.Sub(lastRefresh) < REFRESH_INTERVAL {
				continue
			}
			lastUpdate = t
			lastRefresh = t
			list, err := w.client.NetworkingV1().Ingresses(w.namespace).List(context.TODO(), metav1.ListOptions{})
			if err != nil {
				log.Warningf("call Ingresses list failed: %v", err)
				continue
			}
			// 检查内存和List API查询结果是否一致
			if len(w.entries) == len(list.Items) {
				identical := true
				for _, item := range list.Items {
					if _, in := w.entries[string(item.ObjectMeta.UID)]; !in {
						identical = false
						break
					}
				}
				if identical {
					continue
				}
			}
			log.Debugf("reload %s data", "Ingresses")
			w.m.Lock()
			w.entries = make(map[string]*networkingv1.Ingress)
			for i, item := range list.Items {
				w.entries[string(item.ObjectMeta.UID)] = &list.Items[i]
			}
			w.m.Unlock()
			atomic.AddUint64(&w.version, 1)
		}
	}
	ticker.Stop()
	log.Info("Ingresses watcher stopped")
}

func StartNetworkingV1IngressWatcher(ctx context.Context, client *WatcherClient, namespace string) (Watcher, error) {
	w := &NetworkingV1IngressWatcher{
		ctx: ctx,

		client: client.kubernetes,

		entries:   make(map[string]*networkingv1.Ingress),
		namespace: namespace,
	}
	go w.run()
	return w, nil
}

/*
 * K8s同步watcher
 *     每一个watcher是一个单独的goroutine，由两个channel
 *     发过来的消息触发进行工作。其一是k8s api的watch消息，
 *     当监控的对象发生改变时，channel会收到事件，watcher
 *     只关注add和delete；另一个channel是每隔10分钟的tick，
 *     当watcher 10分钟内没有收到监控对象的添加删除事件时，
 *     会直接调用k8s list api拿到所有监控资源，和内存数据
 *     进行比对。此外，当API watcher退出时，ctx会自动关闭，
 *     watcher也会退出。
 */
type NetworkingV1beta1IngressWatcher struct {
	ctx       context.Context
	client    *kubernetes.Clientset
	namespace string

	m       sync.RWMutex
	entries map[string]*networkingv1beta1.Ingress
	version uint64

	hasError uint32
	errorMsg atomic.Value
}

func (w *NetworkingV1beta1IngressWatcher) Type() string {
	return "IngressWatcher"
}

func (w *NetworkingV1beta1IngressWatcher) Version() uint64 {
	return atomic.LoadUint64(&w.version)
}

func (w *NetworkingV1beta1IngressWatcher) Error() string {
	if atomic.LoadUint32(&w.hasError) == 0 {
		return ""
	}
	atomic.StoreUint32(&w.hasError, 0)
	return w.errorMsg.Load().(string)
}

func (w *NetworkingV1beta1IngressWatcher) Entries() []runtime.Object {
	w.m.RLock()
	entries := make([]runtime.Object, 0, len(w.entries))
	for _, e := range w.entries {
		entries = append(entries, e)
	}
	w.m.RUnlock()
	return entries
}

func (w *NetworkingV1beta1IngressWatcher) run() {
	var watcher watch.Interface
	var err error

	log.Info("Ingresses watcher starting")
PREPARE:
	for {
		select {
		case <-w.ctx.Done():
			log.Info("Ingresses watcher stopped")
			return
		default:
			watcher, err = w.client.NetworkingV1beta1().Ingresses(w.namespace).Watch(w.ctx, metav1.ListOptions{})
			if err == nil {
				break PREPARE
			}
			errMsg := fmt.Sprintf("Ingresses watcher Watch failed: %v", err)
			log.Warning(errMsg)
			w.errorMsg.Store(errMsg)
			atomic.StoreUint32(&w.hasError, 1)
			time.Sleep(time.Minute)
		}
	}

	log.Info("Ingresses watcher started")
	ticker := time.NewTicker(LIST_INTERVAL)
	lastUpdate := time.Now()
	lastRefresh := time.Now()
LOOP:
	for {
		select {
		case <-w.ctx.Done():
			log.Info("Ingresses watcher stopped")
			break LOOP
		case ev, ok := <-watcher.ResultChan():
			if !ok {
				log.Debugf("Ingresses watcher try rewatch")
				newWatcher, err := w.client.NetworkingV1beta1().Ingresses(w.namespace).Watch(w.ctx, metav1.ListOptions{})
				if err != nil {
					errMsg := fmt.Sprintf("Ingresses watcher Watch failed: %v", err)
					log.Warning(errMsg)
					w.errorMsg.Store(errMsg)
					atomic.StoreUint32(&w.hasError, 1)
					time.Sleep(time.Minute)
				} else {
					watcher = newWatcher
				}
				continue LOOP
			}
			if ev.Type == watch.Error {
				if to, ok := ev.Object.(*metav1.Status); ok {
					if strings.Contains(to.Message, "RST_STREAM") {
						// 正常的超时
						log.Debugf("Ingresses watcher timeout rewatch")
						continue
					}
				}
				log.Warningf("Ingresses watcher has error: %v", ev.Object)
				continue
			}
			if ev.Type != watch.Added && ev.Type != watch.Deleted && ev.Type != watch.Modified {
				continue
			}
			el, ok := ev.Object.(*networkingv1beta1.Ingress)
			if !ok {
				continue
			}
			id := string(el.ObjectMeta.UID)
			// 只有删除时检查是否需要更新版本号，其余消息直接更新map内容
			if ev.Type == watch.Deleted {
				if _, in := w.entries[id]; !in {
					continue
				}
				w.m.Lock()
				delete(w.entries, id)
				w.m.Unlock()
			} else {
				w.m.Lock()
				w.entries[id] = el
				w.m.Unlock()
			}
			atomic.AddUint64(&w.version, 1)
			lastUpdate = time.Now()
		case t := <-ticker.C:
			if t.Sub(lastUpdate) < LIST_INTERVAL && t.Sub(lastRefresh) < REFRESH_INTERVAL {
				continue
			}
			lastUpdate = t
			lastRefresh = t
			list, err := w.client.NetworkingV1beta1().Ingresses(w.namespace).List(context.TODO(), metav1.ListOptions{})
			if err != nil {
				log.Warningf("call Ingresses list failed: %v", err)
				continue
			}
			// 检查内存和List API查询结果是否一致
			if len(w.entries) == len(list.Items) {
				identical := true
				for _, item := range list.Items {
					if _, in := w.entries[string(item.ObjectMeta.UID)]; !in {
						identical = false
						break
					}
				}
				if identical {
					continue
				}
			}
			log.Debugf("reload %s data", "Ingresses")
			w.m.Lock()
			w.entries = make(map[string]*networkingv1beta1.Ingress)
			for i, item := range list.Items {
				w.entries[string(item.ObjectMeta.UID)] = &list.Items[i]
			}
			w.m.Unlock()
			atomic.AddUint64(&w.version, 1)
		}
	}
	ticker.Stop()
	log.Info("Ingresses watcher stopped")
}

func StartNetworkingV1beta1IngressWatcher(ctx context.Context, client *WatcherClient, namespace string) (Watcher, error) {
	w := &NetworkingV1beta1IngressWatcher{
		ctx: ctx,

		client: client.kubernetes,

		entries:   make(map[string]*networkingv1beta1.Ingress),
		namespace: namespace,
	}
	go w.run()
	return w, nil
}

/*
 * K8s同步watcher
 *     每一个watcher是一个单独的goroutine，由两个channel
 *     发过来的消息触发进行工作。其一是k8s api的watch消息，
 *     当监控的对象发生改变时，channel会收到事件，watcher
 *     只关注add和delete；另一个channel是每隔10分钟的tick，
 *     当watcher 10分钟内没有收到监控对象的添加删除事件时，
 *     会直接调用k8s list api拿到所有监控资源，和内存数据
 *     进行比对。此外，当API watcher退出时，ctx会自动关闭，
 *     watcher也会退出。
 */
type ExtensionsV1beta1IngressWatcher struct {
	ctx       context.Context
	client    *kubernetes.Clientset
	namespace string

	m       sync.RWMutex
	entries map[string]*extensionsv1beta1.Ingress
	version uint64

	hasError uint32
	errorMsg atomic.Value
}

func (w *ExtensionsV1beta1IngressWatcher) Type() string {
	return "IngressWatcher"
}

func (w *ExtensionsV1beta1IngressWatcher) Version() uint64 {
	return atomic.LoadUint64(&w.version)
}

func (w *ExtensionsV1beta1IngressWatcher) Error() string {
	if atomic.LoadUint32(&w.hasError) == 0 {
		return ""
	}
	atomic.StoreUint32(&w.hasError, 0)
	return w.errorMsg.Load().(string)
}

func (w *ExtensionsV1beta1IngressWatcher) Entries() []runtime.Object {
	w.m.RLock()
	entries := make([]runtime.Object, 0, len(w.entries))
	for _, e := range w.entries {
		entries = append(entries, e)
	}
	w.m.RUnlock()
	return entries
}

func (w *ExtensionsV1beta1IngressWatcher) run() {
	var watcher watch.Interface
	var err error

	log.Info("Ingresses watcher starting")
PREPARE:
	for {
		select {
		case <-w.ctx.Done():
			log.Info("Ingresses watcher stopped")
			return
		default:
			watcher, err = w.client.ExtensionsV1beta1().Ingresses(w.namespace).Watch(w.ctx, metav1.ListOptions{})
			if err == nil {
				break PREPARE
			}
			errMsg := fmt.Sprintf("Ingresses watcher Watch failed: %v", err)
			log.Warning(errMsg)
			w.errorMsg.Store(errMsg)
			atomic.StoreUint32(&w.hasError, 1)
			time.Sleep(time.Minute)
		}
	}

	log.Info("Ingresses watcher started")
	ticker := time.NewTicker(LIST_INTERVAL)
	lastUpdate := time.Now()
	lastRefresh := time.Now()
LOOP:
	for {
		select {
		case <-w.ctx.Done():
			log.Info("Ingresses watcher stopped")
			break LOOP
		case ev, ok := <-watcher.ResultChan():
			if !ok {
				log.Debugf("Ingresses watcher try rewatch")
				newWatcher, err := w.client.ExtensionsV1beta1().Ingresses(w.namespace).Watch(w.ctx, metav1.ListOptions{})
				if err != nil {
					errMsg := fmt.Sprintf("Ingresses watcher Watch failed: %v", err)
					log.Warning(errMsg)
					w.errorMsg.Store(errMsg)
					atomic.StoreUint32(&w.hasError, 1)
					time.Sleep(time.Minute)
				} else {
					watcher = newWatcher
				}
				continue LOOP
			}
			if ev.Type == watch.Error {
				if to, ok := ev.Object.(*metav1.Status); ok {
					if strings.Contains(to.Message, "RST_STREAM") {
						// 正常的超时
						log.Debugf("Ingresses watcher timeout rewatch")
						continue
					}
				}
				log.Warningf("Ingresses watcher has error: %v", ev.Object)
				continue
			}
			if ev.Type != watch.Added && ev.Type != watch.Deleted && ev.Type != watch.Modified {
				continue
			}
			el, ok := ev.Object.(*extensionsv1beta1.Ingress)
			if !ok {
				continue
			}
			id := string(el.ObjectMeta.UID)
			// 只有删除时检查是否需要更新版本号，其余消息直接更新map内容
			if ev.Type == watch.Deleted {
				if _, in := w.entries[id]; !in {
					continue
				}
				w.m.Lock()
				delete(w.entries, id)
				w.m.Unlock()
			} else {
				w.m.Lock()
				w.entries[id] = el
				w.m.Unlock()
			}
			atomic.AddUint64(&w.version, 1)
			lastUpdate = time.Now()
		case t := <-ticker.C:
			if t.Sub(lastUpdate) < LIST_INTERVAL && t.Sub(lastRefresh) < REFRESH_INTERVAL {
				continue
			}
			lastUpdate = t
			lastRefresh = t
			list, err := w.client.ExtensionsV1beta1().Ingresses(w.namespace).List(context.TODO(), metav1.ListOptions{})
			if err != nil {
				log.Warningf("call Ingresses list failed: %v", err)
				continue
			}
			// 检查内存和List API查询结果是否一致
			if len(w.entries) == len(list.Items) {
				identical := true
				for _, item := range list.Items {
					if _, in := w.entries[string(item.ObjectMeta.UID)]; !in {
						identical = false
						break
					}
				}
				if identical {
					continue
				}
			}
			log.Debugf("reload %s data", "Ingresses")
			w.m.Lock()
			w.entries = make(map[string]*extensionsv1beta1.Ingress)
			for i, item := range list.Items {
				w.entries[string(item.ObjectMeta.UID)] = &list.Items[i]
			}
			w.m.Unlock()
			atomic.AddUint64(&w.version, 1)
		}
	}
	ticker.Stop()
	log.Info("Ingresses watcher stopped")
}

func StartExtensionsV1beta1IngressWatcher(ctx context.Context, client *WatcherClient, namespace string) (Watcher, error) {
	w := &ExtensionsV1beta1IngressWatcher{
		ctx: ctx,

		client: client.kubernetes,

		entries:   make(map[string]*extensionsv1beta1.Ingress),
		namespace: namespace,
	}
	go w.run()
	return w, nil
}

/*
 * K8s同步watcher
 *     每一个watcher是一个单独的goroutine，由两个channel
 *     发过来的消息触发进行工作。其一是k8s api的watch消息，
 *     当监控的对象发生改变时，channel会收到事件，watcher
 *     只关注add和delete；另一个channel是每隔10分钟的tick，
 *     当watcher 10分钟内没有收到监控对象的添加删除事件时，
 *     会直接调用k8s list api拿到所有监控资源，和内存数据
 *     进行比对。此外，当API watcher退出时，ctx会自动关闭，
 *     watcher也会退出。
 */
type RouteV1RouteWatcher struct {
	ctx       context.Context
	client    *versioned.Clientset
	namespace string

	m       sync.RWMutex
	entries map[string]*routev1.Route
	version uint64

	hasError uint32
	errorMsg atomic.Value
}

func (w *RouteV1RouteWatcher) Type() string {
	return "RouteWatcher"
}

func (w *RouteV1RouteWatcher) Version() uint64 {
	return atomic.LoadUint64(&w.version)
}

func (w *RouteV1RouteWatcher) Error() string {
	if atomic.LoadUint32(&w.hasError) == 0 {
		return ""
	}
	atomic.StoreUint32(&w.hasError, 0)
	return w.errorMsg.Load().(string)
}

func (w *RouteV1RouteWatcher) Entries() []runtime.Object {
	w.m.RLock()
	entries := make([]runtime.Object, 0, len(w.entries))
	for _, e := range w.entries {
		entries = append(entries, e)
	}
	w.m.RUnlock()
	return entries
}

func (w *RouteV1RouteWatcher) run() {
	var watcher watch.Interface
	var err error

	log.Info("Routes watcher starting")
PREPARE:
	for {
		select {
		case <-w.ctx.Done():
			log.Info("Routes watcher stopped")
			return
		default:
			watcher, err = w.client.RouteV1().Routes(w.namespace).Watch(w.ctx, metav1.ListOptions{})
			if err == nil {
				break PREPARE
			}
			errMsg := fmt.Sprintf("Routes watcher Watch failed: %v", err)
			log.Warning(errMsg)
			w.errorMsg.Store(errMsg)
			atomic.StoreUint32(&w.hasError, 1)
			time.Sleep(time.Minute)
		}
	}

	log.Info("Routes watcher started")
	ticker := time.NewTicker(LIST_INTERVAL)
	lastUpdate := time.Now()
	lastRefresh := time.Now()
LOOP:
	for {
		select {
		case <-w.ctx.Done():
			log.Info("Routes watcher stopped")
			break LOOP
		case ev, ok := <-watcher.ResultChan():
			if !ok {
				log.Debugf("Routes watcher try rewatch")
				newWatcher, err := w.client.RouteV1().Routes(w.namespace).Watch(w.ctx, metav1.ListOptions{})
				if err != nil {
					errMsg := fmt.Sprintf("Routes watcher Watch failed: %v", err)
					log.Warning(errMsg)
					w.errorMsg.Store(errMsg)
					atomic.StoreUint32(&w.hasError, 1)
					time.Sleep(time.Minute)
				} else {
					watcher = newWatcher
				}
				continue LOOP
			}
			if ev.Type == watch.Error {
				if to, ok := ev.Object.(*metav1.Status); ok {
					if strings.Contains(to.Message, "RST_STREAM") {
						// 正常的超时
						log.Debugf("Routes watcher timeout rewatch")
						continue
					}
				}
				log.Warningf("Routes watcher has error: %v", ev.Object)
				continue
			}
			if ev.Type != watch.Added && ev.Type != watch.Deleted && ev.Type != watch.Modified {
				continue
			}
			el, ok := ev.Object.(*routev1.Route)
			if !ok {
				continue
			}
			id := string(el.ObjectMeta.UID)
			// 只有删除时检查是否需要更新版本号，其余消息直接更新map内容
			if ev.Type == watch.Deleted {
				if _, in := w.entries[id]; !in {
					continue
				}
				w.m.Lock()
				delete(w.entries, id)
				w.m.Unlock()
			} else {
				w.m.Lock()
				w.entries[id] = el
				w.m.Unlock()
			}
			atomic.AddUint64(&w.version, 1)
			lastUpdate = time.Now()
		case t := <-ticker.C:
			if t.Sub(lastUpdate) < LIST_INTERVAL && t.Sub(lastRefresh) < REFRESH_INTERVAL {
				continue
			}
			lastUpdate = t
			lastRefresh = t
			list, err := w.client.RouteV1().Routes(w.namespace).List(context.TODO(), metav1.ListOptions{})
			if err != nil {
				log.Warningf("call Routes list failed: %v", err)
				continue
			}
			// 检查内存和List API查询结果是否一致
			if len(w.entries) == len(list.Items) {
				identical := true
				for _, item := range list.Items {
					if _, in := w.entries[string(item.ObjectMeta.UID)]; !in {
						identical = false
						break
					}
				}
				if identical {
					continue
				}
			}
			log.Debugf("reload %s data", "Routes")
			w.m.Lock()
			w.entries = make(map[string]*routev1.Route)
			for i, item := range list.Items {
				w.entries[string(item.ObjectMeta.UID)] = &list.Items[i]
			}
			w.m.Unlock()
			atomic.AddUint64(&w.version, 1)
		}
	}
	ticker.Stop()
	log.Info("Routes watcher stopped")
}

func StartRouteV1RouteWatcher(ctx context.Context, client *WatcherClient, namespace string) (Watcher, error) {
	w := &RouteV1RouteWatcher{
		ctx: ctx,

		client: client.openshift,

		entries:   make(map[string]*routev1.Route),
		namespace: namespace,
	}
	go w.run()
	return w, nil
}
